language: scala
jdk:
    - oraclejdk8
scala:
    - 2.12.1
before_install:
    - sudo apt-get -qq update
    
script: 
    - cd ./scalajs-plugin/
    - chmod +x gradlew
    - ./gradlew install
    - travis_wait 30 ./gradlew build
    - cd ../scalajs-plugin-test/
    - chmod +x gradlew

    - ./gradlew RunJS -Pclassname="com.github.gtache.DummyObject" -Pmethname="printSomething(\"blabla\")" -Prhino
    - ./gradlew RunJS -Pclassname="com.github.gtache.DummyScalaTag" -Pphantom
    - ./gradlew clean
    - ./gradlew RunJS -PtoExec="com.github.gtache.DummyScalaTag().main()" -PrunFull -Prhino
    - ./gradlew clean
    - ./gradlew RunJS -PtoExec="com.github.gtache.DummyObject().main()" -Pclassname="com.github.gtache.DummyScalaTag" -PrunNoOpt
    - ./gradlew clean
    - ./gradlew RunJS -PfileToExec="testjs/testRunWithFile.js" -PrunFull -Pphantom
    - ./gradlew RunJS -PfileToExec="testjs/testRunWithFile.js" -PrunNoOpt -Prhino
    - ./gradlew RunJS -PfileToExec="testjs/testRunWithFile.js"
    - ./gradlew TestJS
    - ./gradlew TestJS -Ptest-only=*JUnit*
    - ./gradlew TestJS -Ptest-only=*Scala* -Prhino
    - ./gradlew TestJS -Pretest -Pphantom


before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/